# 强化学习实验
OpenAI开源的Gym库是一个仿真库，包含很多现有的环境。

In [2]:
import gym

In [7]:
def load_agent():
    agent = Agent()
    agent.load_state_dict(torch.load('agent.pth'))
    agent.eval()
    return agent

In [ ]:
env = gym.make("Taxi-v3")
observation = env.reset()
agent = load_agent() # 函数未定义
for step in range(100):
    action = agent(observation)
    observation, reward, done, info = env.step(action)

In [3]:
# 每个训练中都要使用的返回值有observation，action，reward，done，info
# observation的结构会犹豫游戏的不同而发生变化
# 以CartPole-v0为例
env = gym.make('CartPole-v0') # 创建游戏环境
env.reset() # 重置一个回合
for _ in range(10):
    env.render() # 现实图形界面
    action = env.action_space.sample() # 在该游戏的所有动作空间中随意选择一个作为输出
    '''进一步可由智能体的算法得到'''
    #env.step(action) # 用于提交动作，括号内是具体的动作 有四个返回值
    observation, reward, done, info = env.step(action) # 用于
    print(observation)

env.close() # 关闭环境 注意：如果绘制了实验的图形界面窗口，那么关闭该窗口最佳方式是调用env.close() 试图关闭图形界面窗口可能会导致内存不能释放 甚至会导致死机

/Users/damonchang/opt/anaconda3/envs/pytorch/lib/python3.9/site-packages/gym/envs/registration.py:592: UserWarning: WARN: The environment CartPole-v0 is out of date. You should consider upgrading to version `v1`.
  logger.warn(
/Users/damonchang/opt/anaconda3/envs/pytorch/lib/python3.9/site-packages/gym/core.py:329: DeprecationWarning: WARN: Initializing wrapper in old step API which returns one bool instead of two. It is recommended to set `new_step_api=True` to use new step API. This will be the default behaviour in future.
  deprecation(
/Users/damonchang/opt/anaconda3/envs/pytorch/lib/python3.9/site-packages/gym/wrappers/step_api_compatibility.py:39: DeprecationWarning: WARN: Initializing environment in old step API which returns one bool instead of two. It is recommended to set `new_step_api=True` to use new step API. This will be the default behaviour in future.
  deprecation(
/Users/damonchang/opt/anaconda3/envs/pytorch/lib/python3.9/site-packages/gym/core.py:57: DeprecationWarn

[-0.0324772  -0.17753255 -0.00565475  0.2753821 ]
[-0.03602784  0.01766961 -0.00014711 -0.01907897]
[-0.03567445  0.21279368 -0.00052869 -0.31180832]
[-0.03141858  0.40792316 -0.00676486 -0.60465795]
[-0.02326012  0.21289645 -0.01885802 -0.3141134 ]
[-0.01900219  0.01804814 -0.02514028 -0.02743685]
[-0.01864123 -0.17670442 -0.02568902  0.2572092 ]
[-0.02217531 -0.37145036 -0.02054484  0.54168004]
[-0.02960432 -0.17604578 -0.00971124  0.24259523]
[-0.03312524 -0.37102768 -0.00485933  0.5321992 ]


其中`env.step()`完成了一个完整的$S\rightarrow A\rightarrow R\rightarrow S'$的循环，其中$S'$就是下一个状态，$R$就是当前状态$S$下，执行动作$A$所获得的奖励。只要我们不断观测这样的过程，并让智能体在其中应用相应的算法完成训练，就能得到一个高质量的强化学习模型。

In [16]:
# 查看Gym以注册的环境
# Gym库中的每个环境和动作空间和观测空间
from gym import envs
env_specs = envs.registry.all()
env_ids = [env_spec.id for env_spec in env_specs]
print(len(env_ids),env_ids)

44 ['CartPole-v0', 'CartPole-v1', 'MountainCar-v0', 'MountainCarContinuous-v0', 'Pendulum-v1', 'Acrobot-v1', 'LunarLander-v2', 'LunarLanderContinuous-v2', 'BipedalWalker-v3', 'BipedalWalkerHardcore-v3', 'CarRacing-v2', 'Blackjack-v1', 'FrozenLake-v1', 'FrozenLake8x8-v1', 'CliffWalking-v0', 'Taxi-v3', 'Reacher-v2', 'Reacher-v4', 'Pusher-v2', 'Pusher-v4', 'InvertedPendulum-v2', 'InvertedPendulum-v4', 'InvertedDoublePendulum-v2', 'InvertedDoublePendulum-v4', 'HalfCheetah-v2', 'HalfCheetah-v3', 'HalfCheetah-v4', 'Hopper-v2', 'Hopper-v3', 'Hopper-v4', 'Swimmer-v2', 'Swimmer-v3', 'Swimmer-v4', 'Walker2d-v2', 'Walker2d-v3', 'Walker2d-v4', 'Ant-v2', 'Ant-v3', 'Ant-v4', 'Humanoid-v2', 'Humanoid-v3', 'Humanoid-v4', 'HumanoidStandup-v2', 'HumanoidStandup-v4']


/Users/damonchang/opt/anaconda3/envs/pytorch/lib/python3.9/site-packages/gym/envs/registration.py:421: UserWarning: WARN: The `registry.all` method is deprecated. Please use `registry.values` instead.
  logger.warn(


In [7]:
# 用小车上山MountainCar-v0作为例子
# 学习如何与Gym库进行交互
#import gym
env = gym.make('MountainCar-v0')
print("观测空间 = {}".format(env.observation_space))
print("动作空间 = {}".format(env.action_space))
print("观测空间范围 = ({} ~ {})".format(env.observation_space.low, env.observation_space.high))
print("动作数 = {}".format(env.action_space.n))

观测空间 = Box([-1.2  -0.07], [0.6  0.07], (2,), float32)
动作空间 = Discrete(3)
观测空间范围 = ([-1.2  -0.07] ~ [0.6  0.07])
动作数 = 3


/Users/damonchang/opt/anaconda3/envs/pytorch/lib/python3.9/site-packages/gym/core.py:329: DeprecationWarning: WARN: Initializing wrapper in old step API which returns one bool instead of two. It is recommended to set `new_step_api=True` to use new step API. This will be the default behaviour in future.
  deprecation(
/Users/damonchang/opt/anaconda3/envs/pytorch/lib/python3.9/site-packages/gym/wrappers/step_api_compatibility.py:39: DeprecationWarning: WARN: Initializing environment in old step API which returns one bool instead of two. It is recommended to set `new_step_api=True` to use new step API. This will be the default behaviour in future.
  deprecation(


In [13]:
# 实现智能体控制小车移动
class SimpleAgent():
    def __init__(self, env):
        pass

    def decide(self, observation):
        position, velocity = observation # 获取当前状态 [位置,速度]
        lb = min(-0.09 * (position + 0.25) ** 2 + 0.03,
                 0.3 * (position + 0.9) ** 4 - 0.008)
        rb = -0.07 * (position + 0.38) ** 2 + 0.07
        if lb < velocity < rb:
            action = 2
        else:
            action = 0
        return action
    
    def learn(self, *args):
        pass

agent = SimpleAgent(env)

In [14]:
# 试图让智能体与环境进行交互
def play(env, agent, render=False, train=False):
    episode_reward = 0. # 记录回合总奖励，初始值为0
    observation = env.reset() # 重制游戏环境，开始新回合
    while True: # 不断循环，直到回合结束
        if render: # 是否显示游戏画面
            env.render() # 显示游戏画面
        action = agent.decide(observation)
        next_observation, reward, done, info = env.step(action) # 执行动作
        episode_reward += reward # 收集回合总奖励
        if train: # 判断是否需要训练
            agent.learn(observation, action, reward, done) # 学习
        if done: # 回合结束，跳出循环
            break
        observation = next_observation
    return episode_reward # 返回回合总奖励

In [15]:
# 让智能体和环境交互一个回合 并现实图形界面
env.seed(3) # 设计随机种子 让结果可复现
episode_reward = play(env, agent, render=True)
print("回合奖励 = {}".format(episode_reward))
env.close() #关闭图形界面

/Users/damonchang/opt/anaconda3/envs/pytorch/lib/python3.9/site-packages/gym/core.py:268: DeprecationWarning: WARN: Function `env.seed(seed)` is marked as deprecated and will be removed in the future. Please use `env.reset(seed=seed)` instead.
  deprecation(
/Users/damonchang/opt/anaconda3/envs/pytorch/lib/python3.9/site-packages/gym/core.py:57: DeprecationWarning: WARN: You are calling render method, but you didn't specified the argument render_mode at environment initialization. To maintain backward compatibility, the environment will render in human mode.
If you want to render in human mode, initialize the environment in this way: gym.make('EnvName', render_mode='human') and don't call the render method.
See here for more information: https://www.gymlibrary.ml/content/api/
  deprecation(
2025-02-28 21:30:16.159 python[29341:1566945] _TIPropertyValueIsValid called with 11 on nil context!
2025-02-28 21:30:16.159 python[29341:1566945] imkxpc_setApplicationProperty:value:reply: called w

回合奖励 = -104.0


2025-02-28 21:30:20.650 python[29341:1566945] _TIPropertyValueIsValid called with 12 on nil context!
2025-02-28 21:30:20.650 python[29341:1566945] imkxpc_setApplicationProperty:value:reply: called with incorrect property value 12, bailing.
